# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true


# Setup
title:               HycJack's Blog
tagline:             '天行健，君子以自强不息；地势坤，君子以厚德载物'
description:         'Hello World  代码之路，路漫漫其修远兮，吾将上下而求索'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            8

# About/contact
author:              	
  name:              HycJack
  url:               https://hycjack.github.io/
  email:             772403255@qq.com

# Custom vars
version:             1.0.0

plugins:
  - jekyll-paginate
